[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = 'concurrent-search-bot'
version = '0.1.0'
description = 'Educational pet-prjct'
requires-python = ">=3.11,<3.15"
dependencies = ["aiogram==3.31.0", "aiohttp>=3.9,<4"]

[tool.setuptools.packages.find]
where = ["src"]
